#!/usr/bin/env python3
"""Live Scanner — Scans for signals from the top 3 swing strategies:
  1. MA Bounce (pullback to EMA20 in uptrend)
  2. Breakout (20-day high break above SMA50)
  3. Higher High Break (first HH after 3+ lower swing highs)

Usage:
    python3 scripts/scan_live.py                          # Scan ~50 swing stocks
    python3 scripts/scan_live.py --universe sp500         # Scan S&P 500
    python3 scripts/scan_live.py --tickers AAPL NVDA TSLA # Specific tickers
    python3 scripts/scan_live.py --file watchlist.txt     # From file
"""
import argparse
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import yfinance as yf

OUT = Path(__file__).resolve().parent.parent / "dashboard" / "public" / "live_scanner_data.json"

# ── Stock Universes ──
SWING_STOCKS = [
    'SPY','QQQ','AAPL','ADBE','AMD','AMZN','BA','CRM','GOOGL','META','MSFT','NVDA',
    'SNOW','TSLA','NFLX','SHOP','SQ','PLTR','COIN','SOFI','RIVN','NIO','MARA',
    'SMCI','ARM','MRVL','AVGO','MU','ANET','CRWD','PANW','NET','DDOG','TTD',
    'RBLX','U','SE','PINS','SNAP','UBER','LYFT','ABNB','DASH','ROKU','ZM',
    'ENPH','FSLR','RUN','PLUG','LCID',
]

SP500_FALLBACK = [
    'AAPL','ABBV','ABT','ACN','ADBE','ADI','ADP','ADSK','AEP','AFL','AIG','AMAT','AMD','AMGN',
    'AMZN','ANET','ANSS','APD','APH','AVGO','AXP','BA','BAC','BDX','BK','BKNG','BLK','BMY',
    'BRK-B','BSX','C','CAT','CB','CCI','CDNS','CDW','CEG','CHTR','CI','CL','CMCSA','CME',
    'CMG','COP','COST','CRM','CRWD','CSCO','CTAS','CTSH','CVX','D','DASH','DD','DE','DHR',
    'DIS','DLR','DOW','DUK','DVN','DXCM','EA','EBAY','ECL','EL','EMR','ENPH','EOG','EQIX',
    'EW','EXC','F','FAST','FCX','FDX','FI','FICO','FTNT','GD','GE','GEHC','GEV','GILD',
    'GM','GOOG','GOOGL','GS','HD','HON','HPQ','HUM','IBM','ICE','IDXX','ILMN','INTC','INTU',
    'ISRG','IT','JCI','JNJ','JPM','KDP','KEY','KHC','KKR','KLAC','KMI','KO','LHX','LIN',
    'LLY','LMT','LOW','LRCX','LULU','LVS','MA','MAR','MCD','MCHP','MCK','MCO','MDLZ','MDT',
    'MET','META','MMC','MMM','MNST','MO','MOH','MPC','MRK','MRNA','MS','MSFT','MSI','MU',
    'NDAQ','NFLX','NKE','NOC','NOW','NSC','NTAP','NVDA','NVO','ORCL','ORLY','OXY','PANW',
    'PAYX','PCAR','PEP','PFE','PG','PGR','PH','PLTR','PM','PNC','PODD','PSA','PSX','PXD',
    'PYPL','QCOM','REGN','ROP','ROST','RTX','SBUX','SCHW','SHW','SLB','SMH','SMCI','SNPS',
    'SO','SPG','SPGI','SQ','SRE','SYK','SYY','T','TDG','TFC','TGT','TJX','TMO','TMUS',
    'TSLA','TSN','TT','TTD','TXN','TYL','UNH','UNP','UPS','URI','USB','V','VICI','VLO',
    'VRSK','VRTX','VZ','WBA','WDAY','WEC','WELL','WFC','WM','WMT','XEL','XOM','ZTS'
]

NASDAQ100_FALLBACK = [
    'AAPL','ABNB','ADBE','ADI','ADP','ADSK','AEP','AMAT','AMD','AMGN','AMZN','ANSS','ARM',
    'ASML','AVGO','AZN','BIIB','BKNG','BKR','CCEP','CDNS','CDW','CEG','CHTR','CMCSA','COST',
    'CPRT','CRWD','CSCO','CSGP','CTAS','CTSH','DASH','DDOG','DLTR','DXCM','EA','EXC','FANG',
    'FAST','FTNT','GEHC','GFS','GILD','GOOG','GOOGL','HON','IDXX','ILMN','INTC','INTU','ISRG',
    'KDP','KHC','KLAC','LIN','LRCX','LULU','MAR','MCHP','MDB','MDLZ','MELI','META','MNST',
    'MRVL','MSFT','MU','NFLX','NVDA','NXPI','ODFL','ON','ORLY','PANW','PAYX','PCAR','PDD',
    'PEP','PYPL','QCOM','REGN','ROP','ROST','SBUX','SMCI','SNPS','SPLK','TEAM','TMUS','TSLA',
    'TTD','TTWO','TXN','VRSK','VRTX','WBD','WDAY','XEL','ZS'
]


UNIVERSE_FILE = Path(__file__).resolve().parent.parent / "data" / "stock_universe.json"


def get_universe(name):
    if name == 'universe':
        # Use the pre-built universe file (generated by build_universe.py)
        if UNIVERSE_FILE.exists():
            import json
            data = json.load(open(UNIVERSE_FILE))
            print(f"  Loaded {data['count']} stocks from {UNIVERSE_FILE.name} (built {data['generatedAt']})")
            return data['tickers']
        else:
            print("  ⚠ Universe file not found, falling back to S&P 500")
            return get_universe('sp500')
    elif name == 'sp500':
        try:
            table = pd.read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies", header=0)[0]
            return sorted(table['Symbol'].str.replace('.', '-', regex=False).tolist())
        except Exception:
            return SP500_FALLBACK
    elif name == 'nasdaq100':
        return NASDAQ100_FALLBACK
    else:
        return SWING_STOCKS


def download_data(tickers, period='1y'):
    """Bulk download daily OHLCV data."""
    print(f"  📥 Downloading {len(tickers)} stocks ({period})...")
    batch_size = 50
    all_data = {}

    for i in range(0, len(tickers), batch_size):
        batch = tickers[i:i+batch_size]
        try:
            df = yf.download(batch, period=period, interval='1d',
                           group_by='ticker', progress=False, threads=True)
            if len(batch) == 1:
                ticker = batch[0]
                if not df.empty:
                    all_data[ticker] = df.reset_index()
            else:
                for ticker in batch:
                    try:
                        tdf = df[ticker].dropna(how='all').reset_index()
                        if len(tdf) > 60:
                            all_data[ticker] = tdf
                    except (KeyError, TypeError):
                        pass
        except Exception as e:
            print(f"    ⚠ Batch error: {e}")

    print(f"  ✅ Got data for {len(all_data)}/{len(tickers)} stocks")
    return all_data


def normalize_df(df):
    """Normalize column names from yfinance output."""
    if 'Date' not in df.columns and df.index.name == 'Date':
        df = df.reset_index()
    col_map = {}
    for c in df.columns:
        cl = str(c).lower()
        if cl == 'date': col_map[c] = 'Date'
        elif cl == 'open': col_map[c] = 'Open'
        elif cl == 'high': col_map[c] = 'High'
        elif cl == 'low': col_map[c] = 'Low'
        elif cl in ('close', 'adj close'): col_map[c] = 'Close'
        elif cl == 'volume': col_map[c] = 'Volume'
    df = df.rename(columns=col_map)
    return df


def add_indicators(df):
    """Add all indicators needed for the 3 strategies."""
    df = df.copy()
    df['ema20'] = df['Close'].ewm(span=20, adjust=False).mean()
    df['sma50'] = df['Close'].rolling(50).mean()

    # ATR
    tr = np.maximum(df['High'] - df['Low'],
        np.maximum(np.abs(df['High'] - df['Close'].shift(1)),
                   np.abs(df['Low'] - df['Close'].shift(1))))
    df['atr'] = tr.rolling(14).mean()

    # 20-day high (for Breakout)
    df['high_20'] = df['High'].rolling(20).max().shift(1)

    return df


def find_swing_highs(df, window=10):
    """Find swing highs for Higher High detection."""
    highs = []
    high_col = df['High'].values
    for i in range(window, len(df) - window):
        local_max = high_col[i-window:i+window+1].max()
        if high_col[i] == local_max:
            highs.append((i, float(high_col[i])))
    filtered = []
    for h in highs:
        if not filtered or h[0] - filtered[-1][0] >= window:
            filtered.append(h)
    return filtered


def scan_ma_bounce(df, ticker, lookback=5):
    """MA Bounce: Pullback to EMA20 in uptrend, bounce off it."""
    signals = []
    n = len(df)

    for i in range(max(50, n - lookback), n):
        row = df.iloc[i]
        prev = df.iloc[i - 1]

        if pd.isna(row['sma50']) or pd.isna(row['ema20']) or pd.isna(row['atr']):
            continue

        atr = row['atr']
        if atr <= 0:
            continue

        # Entry conditions:
        # 1. Uptrend: close > SMA50
        if row['Close'] <= row['sma50']:
            continue

        # 2. Previous bar low dipped near EMA20 (within 0.5 ATR)
        if prev['Low'] > prev['ema20'] + 0.5 * atr:
            continue

        # 3. Current bar closes above EMA20
        if row['Close'] <= row['ema20']:
            continue

        # 4. Not overextended (close not > 3 ATR above EMA20)
        if row['Close'] > row['ema20'] + 3 * atr:
            continue

        # 5. Not a huge gap bar
        bar_range = row['High'] - row['Low']
        if bar_range > 2 * atr:
            continue

        entry = row['Close']
        stop = entry - atr
        risk = entry - stop
        date_str = row['Date'].strftime('%Y-%m-%d') if hasattr(row['Date'], 'strftime') else str(row['Date'])[:10]

        signals.append({
            'ticker': ticker,
            'strategy': 'MA Bounce',
            'date': date_str,
            'entry': round(entry, 2),
            'stop': round(stop, 2),
            'risk_per_share': round(risk, 2),
            'details': f"Bounced off EMA20 (${row['ema20']:.2f}) in uptrend (SMA50=${row['sma50']:.2f})",
            'strength': 'STRONG' if row['Close'] > row['sma50'] * 1.03 else 'NORMAL',
            'bars_ago': n - 1 - i,
        })

    return signals


def scan_breakout(df, ticker, lookback=5):
    """Breakout: Close above 20-day high, above SMA50."""
    signals = []
    n = len(df)

    for i in range(max(50, n - lookback), n):
        row = df.iloc[i]

        if pd.isna(row['sma50']) or pd.isna(row['high_20']) or pd.isna(row['atr']):
            continue

        atr = row['atr']
        if atr <= 0:
            continue

        # Entry conditions:
        # 1. Above SMA50
        if row['Close'] <= row['sma50']:
            continue

        # 2. Close breaks above 20-day high
        if row['Close'] <= row['high_20']:
            continue

        # 3. Not a huge gap bar
        bar_range = row['High'] - row['Low']
        if bar_range > 2.5 * atr:
            continue

        entry = row['Close']
        stop = entry - atr
        risk = entry - stop
        date_str = row['Date'].strftime('%Y-%m-%d') if hasattr(row['Date'], 'strftime') else str(row['Date'])[:10]

        signals.append({
            'ticker': ticker,
            'strategy': 'Breakout',
            'date': date_str,
            'entry': round(entry, 2),
            'stop': round(stop, 2),
            'risk_per_share': round(risk, 2),
            'details': f"Broke 20d high ${row['high_20']:.2f}, above SMA50 (${row['sma50']:.2f})",
            'strength': 'STRONG' if row['Close'] > row['high_20'] * 1.02 else 'NORMAL',
            'bars_ago': n - 1 - i,
        })

    return signals


def scan_higher_high(df, ticker, lookback=30):
    """Higher High Break: First HH after 3+ consecutive lower swing highs."""
    signals = []
    n = len(df)

    if n < 100:
        return signals

    swing_highs = find_swing_highs(df, window=10)
    if len(swing_highs) < 4:
        return signals

    for sh_idx in range(3, len(swing_highs)):
        lower_count = 0
        for j in range(sh_idx - 1, 0, -1):
            if swing_highs[j][1] < swing_highs[j-1][1]:
                lower_count += 1
            else:
                break

        if lower_count < 3:
            continue

        curr_sh = swing_highs[sh_idx]
        prev_sh = swing_highs[sh_idx - 1]

        if curr_sh[1] <= prev_sh[1]:
            continue

        if curr_sh[0] < n - lookback:
            continue

        bar_idx = curr_sh[0]
        close = df['Close'].values
        atr_vals = df['atr'].values
        entry = close[bar_idx]
        atr_val = atr_vals[bar_idx] if not np.isnan(atr_vals[bar_idx]) else 0
        stop = entry - atr_val if atr_val > 0 else df['Low'].values[bar_idx]
        risk = entry - stop
        break_pct = (curr_sh[1] - prev_sh[1]) / prev_sh[1] * 100

        lower_highs = [swing_highs[j][1] for j in range(max(0, sh_idx - lower_count), sh_idx)]

        date_val = df.iloc[bar_idx]['Date']
        date_str = date_val.strftime('%Y-%m-%d') if hasattr(date_val, 'strftime') else str(date_val)[:10]

        signals.append({
            'ticker': ticker,
            'strategy': 'Higher High',
            'date': date_str,
            'entry': round(entry, 2),
            'stop': round(stop, 2),
            'risk_per_share': round(risk, 2),
            'details': f"First HH after {lower_count} lower highs. Broke ${prev_sh[1]:.2f}. LHs: {' → '.join(f'${h:.0f}' for h in lower_highs[-4:])}",
            'strength': 'STRONG' if break_pct > 3 else 'NORMAL',
            'bars_ago': n - 1 - bar_idx,
        })

    return signals


def main():
    parser = argparse.ArgumentParser(description='Live Scanner — Top 3 Swing Strategies')
    parser.add_argument('--universe', choices=['sp500', 'nasdaq100', 'swing', 'universe'], default='swing',
                       help='Stock universe (default: swing). "universe" uses data/stock_universe.json')
    parser.add_argument('--tickers', nargs='+', help='Specific tickers')
    parser.add_argument('--file', type=str, help='File with tickers (one per line)')
    parser.add_argument('--period', default='1y', help='Data period (default: 1y)')
    parser.add_argument('--lookback', type=int, default=5, help='Bars to look back for MA Bounce & Breakout (default: 5)')
    parser.add_argument('--hh-lookback', type=int, default=30, help='Bars to look back for Higher High (default: 30)')
    args = parser.parse_args()

    print("=" * 60)
    print("  🔴🔵🟡 LIVE SCANNER — Top 3 Swing Strategies")
    print("=" * 60)
    print(f"  Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print(f"  Strategies: MA Bounce | Breakout | Higher High Break")
    print(f"  Lookback: {args.lookback} bars (bounce/breakout), {args.hh_lookback} bars (higher high)")
    print()

    # Get tickers
    if args.tickers:
        tickers = [t.upper() for t in args.tickers]
    elif args.file:
        tickers = [l.strip().upper() for l in open(args.file) if l.strip()]
    else:
        tickers = get_universe(args.universe)
        print(f"  Universe: {args.universe} ({len(tickers)} stocks)")

    print()

    # Download
    data = download_data(tickers, period=args.period)
    if not data:
        print("  ❌ No data. Check internet.")
        sys.exit(1)

    # Scan
    print(f"\n  🔍 Scanning...")
    all_signals = []

    for ticker, df in data.items():
        df = normalize_df(df)
        if 'High' not in df.columns or 'Close' not in df.columns:
            continue
        df = add_indicators(df)

        all_signals.extend(scan_ma_bounce(df, ticker, lookback=args.lookback))
        all_signals.extend(scan_breakout(df, ticker, lookback=args.lookback))
        all_signals.extend(scan_higher_high(df, ticker, lookback=args.hh_lookback))

    # Deduplicate: if same ticker has multiple signals on same day for same strategy, keep latest
    seen = set()
    deduped = []
    for s in sorted(all_signals, key=lambda x: (x['date'], x['ticker']), reverse=True):
        key = (s['ticker'], s['strategy'], s['date'])
        if key not in seen:
            seen.add(key)
            deduped.append(s)
    all_signals = deduped

    # Sort by date desc, then strategy
    all_signals.sort(key=lambda s: (s['date'], s['strategy']), reverse=True)

    # Group by strategy for summary
    by_strat = {}
    for s in all_signals:
        by_strat.setdefault(s['strategy'], []).append(s)

    # Print results
    print("\n" + "=" * 60)
    print(f"  📊 RESULTS: {len(all_signals)} signals across {len(data)} stocks")
    print("=" * 60)

    for strat_name, strat_signals in sorted(by_strat.items()):
        icon = {'MA Bounce': '🔵', 'Breakout': '🟡', 'Higher High': '📐'}[strat_name]
        print(f"\n  {icon} {strat_name} — {len(strat_signals)} signals")
        print(f"  {'─' * 50}")
        print(f"  {'Ticker':<8} {'Date':<12} {'Entry':>8} {'Stop':>8} {'Risk':>7} {'Str':<7}")
        for s in strat_signals[:15]:
            print(f"  {s['ticker']:<8} {s['date']:<12} ${s['entry']:>6.2f} ${s['stop']:>6.2f} ${s['risk_per_share']:>4.2f}  {s['strength']}")
        if len(strat_signals) > 15:
            print(f"  ... +{len(strat_signals) - 15} more")

    # Also show combined "today's picks" — signals from most recent date
    if all_signals:
        latest_date = all_signals[0]['date']
        todays = [s for s in all_signals if s['date'] == latest_date]
        if todays:
            print(f"\n  🎯 LATEST SIGNALS ({latest_date}): {len(todays)} picks")
            print(f"  {'─' * 50}")
            for s in todays:
                icon = {'MA Bounce': '🔵', 'Breakout': '🟡', 'Higher High': '📐'}[s['strategy']]
                print(f"  {icon} {s['ticker']:<8} {s['strategy']:<14} Entry ${s['entry']} | Stop ${s['stop']} | Risk ${s['risk_per_share']}")

    # Stocks picked by multiple strategies
    ticker_strats = {}
    for s in all_signals:
        ticker_strats.setdefault(s['ticker'], set()).add(s['strategy'])
    multi = {t: strats for t, strats in ticker_strats.items() if len(strats) >= 2}
    if multi:
        print(f"\n  ⭐ CONFLUENCE — Stocks picked by multiple strategies:")
        for t, strats in sorted(multi.items(), key=lambda x: -len(x[1])):
            print(f"    {t}: {' + '.join(sorted(strats))}")

    # Save JSON
    import json
    output = {
        'scanDate': datetime.now().strftime('%Y-%m-%d %H:%M'),
        'universe': args.universe if not args.tickers else 'custom',
        'stocksScanned': len(data),
        'totalSignals': len(all_signals),
        'signals': all_signals,
        'byStrategy': {
            'MA Bounce': [s for s in all_signals if s['strategy'] == 'MA Bounce'],
            'Breakout': [s for s in all_signals if s['strategy'] == 'Breakout'],
            'Higher High': [s for s in all_signals if s['strategy'] == 'Higher High'],
        },
        'confluence': [
            {'ticker': t, 'strategies': sorted(list(strats))}
            for t, strats in sorted(multi.items(), key=lambda x: -len(x[1]))
        ] if multi else [],
        'summary': {
            'MA Bounce': len(by_strat.get('MA Bounce', [])),
            'Breakout': len(by_strat.get('Breakout', [])),
            'Higher High': len(by_strat.get('Higher High', [])),
        }
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, 'w') as f:
        json.dump(output, f, indent=2, default=str)
    print(f"\n  💾 Saved to: {OUT}")
    print()


if __name__ == '__main__':
    main()
